### ISSUE TITLE
URI decode error

### ISSUE THREAD

**Issue by jacepark12** [Y-Scholars/db.kscy.org_Front#5]
URIError: Failed to decode param '/%%7Buid%7D'
    at decodeURIComponent (native)
    at decode_param (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:317:13)
    at /Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/middleware/query.js:44:5)
    at Layer.handle [as handle_request] (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:317:13)
    at /Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/router/index.js:174:3)
    at EventEmitter.handle (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/application.js:174:10)
    at Server.app (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/express/lib/express.js:38:9)
    at Server.new_handler (/Users/parkjaesung/Documents/workspace/Github/YSchola/YScholars_Front/node_modules/sockjs/lib/utils.js:89:20)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

request URI : http://localhost:4200/%%7Buid%7D

검색후 발표논문 클릭시 오류

**Comment by enoxaiming** [comment]
지금은 해결됨?
